exclude: '^docs/.*$'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: flake8
        additional_dependencies:
        -   flake8
        -   flake8-tidy-imports
