exclude: '^docs/.*$'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: flake8
        additional_dependencies:
        -   flake8==3.3.0
        -   flake8-tidy-imports==1.0.6
