exclude: '^docs/.*$'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: flake8
        additional_dependencies:
        -   flake8
        -   flake8-tidy-imports
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
    -   id: mypy
        additional_dependencies:
        -   --no-compile
        -   cffi==1.15.1
        -   cryptography==41.0.1
        -   pycparser==2.21
        -   types-pyopenssl==23.2.0.1
        -   types-pytz==2023.3.0.0
        -   types-pyyaml==6.0.12.10
        -   types-redis==4.6.0.0
        -   types-requests==2.31.0.1
        -   types-urllib3==1.26.25.13
