exclude: '^docs/.*$'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: flake8
        additional_dependencies:
        -   flake8
        -   flake8-tidy-imports
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
    -   id: mypy
        additional_dependencies:
        -   --no-compile
        -   cffi==1.16.0
        -   cryptography==43.0.0
        -   pycparser==2.22
        -   types-cffi==1.16.0.20240331
        -   types-pyopenssl==24.1.0.20240722
        -   types-pytz==2024.1.0.20240417
        -   types-pyyaml==6.0.12.20240724
        -   types-redis==4.6.0.20240425
        -   types-setuptools==71.1.0.20240724
